{
 "title": "ssl-expiry",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Certificates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ssl_cert_days_left)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "More than 30 days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ssl_cert_days_left > 30)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Days left [30-20]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssl_cert_days_left >= 20 and ssl_cert_days_left <= 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days left [20-10]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssl_cert_days_left >= 10 and ssl_cert_days_left <= 19)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Days left [10-1]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ssl_cert_days_left >= 1 and ssl_cert_days_left <= 9)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fatality",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ssl_cert_days_left <= 0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Certificate analytics",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{__name__=\"ssl_cert_days_left\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ssl_cert_start_timestamp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ssl_cert_end_timestamp\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{__name__=\"ssl_cert_error_text\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}