version: "3.8"

services:
  ssl-exporter:
    image: imitatop/ssl-exporter_mongo:latest
    ports:
      - "9115:9115"
    networks:
      - proxy-net
      - proxy-bot
    secrets:
      - source: mongo_root_username
        target: mongo_user
      - source: mongo_root_password
        target: mongo_password
    environment:
      MONGO_HOST: db_mongo
      MONGO_DB: ssl
      MONGO_COLLECTION: domains
      MONGO_USER_FILE: /run/secrets/mongo_user
      MONGO_PASSWORD_FILE: /run/secrets/mongo_password
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  mongo_root_username:
    external: true
  mongo_root_password:
    external: true

networks:
  proxy-net:
    external: true
  proxy-bot:
    external: true


